name: boxey_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-54.0.dev <14.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.1.0
  protobuf: ^2.1.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  go_router: ^6.0.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator: ^1.1.1
  go_router_builder: ^1.0.15
  freezed: ^2.3.2

flutter:
  uses-material-design: true
