// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file auth.proto (package boxey.auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UserRegisterReply, UserRegisterRequest } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service boxey.auth.UserAuth
 */
export const UserAuth = {
  typeName: "boxey.auth.UserAuth",
  methods: {
    /**
     * @generated from rpc boxey.auth.UserAuth.Register
     */
    register: {
      name: "Register",
      I: UserRegisterRequest,
      O: UserRegisterReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

