// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file packages.proto (package boxey.packages, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PackageDetailsReply, PackageDetailsRequest, PackageListReply, PackageListRequest } from "./packages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service boxey.packages.Packages
 */
export const Packages = {
  typeName: "boxey.packages.Packages",
  methods: {
    /**
     * @generated from rpc boxey.packages.Packages.PackageList
     */
    packageList: {
      name: "PackageList",
      I: PackageListRequest,
      O: PackageListReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc boxey.packages.Packages.PackageDetails
     */
    packageDetails: {
      name: "PackageDetails",
      I: PackageDetailsRequest,
      O: PackageDetailsReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

