// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file sending.proto (package boxey.sending, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PackageSendReply, PackageSendRequest, SizeListReply, SizeListRequest } from "./sending_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service boxey.sending.PackageSending
 */
export const PackageSending = {
  typeName: "boxey.sending.PackageSending",
  methods: {
    /**
     * @generated from rpc boxey.sending.PackageSending.PackageSend
     */
    packageSend: {
      name: "PackageSend",
      I: PackageSendRequest,
      O: PackageSendReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc boxey.sending.PackageSending.SizeList
     */
    sizeList: {
      name: "SizeList",
      I: SizeListRequest,
      O: SizeListReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

