// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file webtrack.proto (package boxey.webtrack, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TrackPackageReply, TrackPackageRequest } from "./webtrack_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service boxey.webtrack.WebTrack
 */
export const WebTrack = {
  typeName: "boxey.webtrack.WebTrack",
  methods: {
    /**
     * @generated from rpc boxey.webtrack.WebTrack.TrackPackage
     */
    trackPackage: {
      name: "TrackPackage",
      I: TrackPackageRequest,
      O: TrackPackageReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

